server.port=8080
server.connection-timeout=300000
server.error.include-message=always


token.user.name=eulerUser
token.user.password=5Am@OpenEuler#94Community
token.base.password=b79rog4380b0fdasdfyuiofasd
token.expire.seconds=60

spring.cache.ttl=86400
## -- redis start --
spring.data.redis.database=0
spring.data.redis.host=127.0.0.1
spring.data.redis.port=6379
spring.data.redis.password=openEuler@123
spring.data.redis.jedis.pool.max-active=-1
spring.data.redis.jedis.pool.max-wait=-1
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0
spring.data.redis.timeout=5000
spring.data.redis.key.expire=3600
spring.data.redis.listen-pattern: __keyevent@0__:expired
## -- end start --

## -- Authing start --
authing.userPoolId=6219de6ce6bfeabc92071991
authing.secret=d5a008f7337a1e159bc91224a7a76379
authing.token.base.password=qwecvgy678unjiom
authing.token.expire.seconds=1800
authing.cookie.max.age=-1
old.token.expire.seconds=60
login.error.limit.count=6
login.error.limit.seconds=60
need.captcha.limit.count=5
username.reserved=mindspore,openeuler,models,datasets,settings,notfound,privacy,legal,organizations,404,gradio,modelarts,aim,train,huawei
openeuler.sigRead=62845f26b7dbf20f7890c0ad->SIG:*->SIG:read
openeuler.groupCode=62845f26b7dbf20f7890c0ad
openeuler.companyAction=read_all
authing.api.host=https://core.authing.cn
authing.api.hostv2=https://core.authing.cn/api/v2
authing.api.hostv3=https://api.authing.cn/api/v3
github.users.api=https://api.github.com/users/
owner.type.api=https://dsapi.osinfra.cn/query/user/ownertype?community=openeuler&user=%s
## -- Authing end --

## -- obs start --
datastat.img.ak=DLAZVGG1GBVRCJC4IT3Y
datastat.img.sk=fYZnPQIhHJLotsoACdkw8Cwaq3NNdzC6rtfgnzEG
datastat.img.endpoint=obs.ap-southeast-1.myhuaweicloud.com
datastat.img.bucket.name=datastat-img
datastat.img.default.photo=default-user-photo.png
datastat.img.photo.suffix=.jpg;.png
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
spring.mvc.hiddenmethod.filter.enabled=true
## -- obs end --

## -- email server start --
spring.mail.host=smtp.exmail.qq.com
spring.mail.username=id@public.osinfra.cn
spring.mail.password=SiDEjnvumB8Tfp7T
spring.mail.port=465
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
mail.code.expire=300
mail.template.expire.minutes=5
## -- email server end --

send.code.limit.seconds=60

## -- ??? MSGSMS start --
msgsms.app_key=C5I7EH4iPr4xPXRNa65Qg70bATxP
msgsms.app_secret=slpTMyXRJdAOldFm2bw6fxdtpoQy
msgsms.url=https://smsapi.cn-south-1.myhuaweicloud.com:443/sms/batchSendSms/v1
msgsms.signature=??????
msgsms.sender=8823032852411
msgsms.template.id=7fd0d062f58143069e31399117825588

opengauss.msgsms.app_key=jAW0XfBRgQAk9fg4x3r4DxNKNial
opengauss.msgsms.app_secret=ALW50QsAd4jyp416pgAE706bR8EP
opengauss.msgsms.url=https://smsapi.cn-south-1.myhuaweicloud.com:443/sms/batchSendSms/v1
opengauss.msgsms.signature=?openGauss?
opengauss.msgsms.sender=8823022827238
opengauss.msgsms.template.id=4d3f4056bb8d470097052eb02b23db52

opengauss.app.urls=90aa315f895544359209920da32ff75a:opengauss.org,osinfra.cn,myopeninfra.com

msgsms.code.expire=300
msgsms.template.expire.minutes=5
code.length=6

sms.international.countrys.code=+61,+34,+39,+33,+86
## -- ??? MSGSMS end --

## -- ????? start --
aj.captcha.jigsaw=classpath:images/jigsaw
aj.captcha.pic-click=classpath:images/pic-click
aj.captcha.cache-type=redis
aj.captcha.type=blockPuzzle
aj.captcha.water-mark=\u3000
## -- ????? end --

## -- Authing ?????? start --
social.extIdpId.github=6226db30ab45976d1023a8cb
social.connId.github=6226db30c8e30db1518cc4aa
social.identifier.github=001
social.authorizationUrl.github=https://core.authing.cn/connections/social/%s?app_id=%s&is_bind=1&from_guard=1&user_token=%s
## -- Authing ?????? end --

social.extIdpId.wechat=662605f0ef726df2517b6a47
social.connId.wechat=662605f0fd03c1fba569a6ce
social.identifier.wechat=wechat
social.authorizationUrl.wechat=https://core.authing.cn/connections/social/%s?app_id=%s&is_bind=1&from_guard=1&user_token=%s

## -- Authing ????? start --
enterprise.extIdpId.gitee=6226d911e5b246c2dbc9ba08
enterprise.connId.gitee=6226d91103d81d8654673f1b
enterprise.identifier.gitee=gitee
enterprise.authorizationUrl.gitee=https://core.authing.cn/connections/oauth2/init?app_id=%s&is_bind=1&from_guard=1&identifier=%s&user_token=%s

enterprise.extIdpId.openatom=63c0bfd4f510160d2771c3b3
enterprise.connId.openatom=63c0bfd4c88ee67bcf1959b4
enterprise.identifier.openatom=openatom
enterprise.authorizationUrl.openatom=https://core.authing.cn/connections/oauth2/init?app_id=%s&is_bind=1&from_guard=1&identifier=%s&user_token=%s
## -- Authing ????? end --

## -- RSA start --
rsa.authing.publicKey=MIIBojANBgkqhkiG9w0BAQEFAAOCAY8AMIIBigKCAYEAr4gV-MbNe-3G7FF_8O4YyWC8gRcNH5cUekaGqyRsooj-ulV9-Td5mRh8hQB6P61TwRN4_SjIAoIhxkjV8WF2RQx6uPV0vFkK-jw8WnZtiImJFF4B-pHX2pOvOHFf_lnpWFzJ0J_wYkmOpzyfmFRM4pB_0ssoPFMEZvTq1myRF94rrtgzgEndJDPB3X9Pa5lRpP8tCPVoRn4O-xdQ3q_pjUmhHOh8STjpmXetjk_UhxdbJIk7zaW9RjxowSD-ftVYvCdDO8Ju4gD_0nJ5krH__cIyNCMaZYGH9Pdsu6CsHfqo7lclIXQj_zpZ4D77H4AEHWnedsvZS0PONskbPCKGZPSd12zQxzI9zdGzXid0RlM4iJwjfHEnUdU5PQalc2rxD61V5vLTD5B8uUfWrQ2pk2pUoPeB2tg1VKZK1HaGW9WUh_e-Eit7XWy4sbab_GBejHP83xP-ADUQhqYwqzoXYxdEDarOd3yKbXzFKEU7XyxX3TS3_Uinp_6ngX85L1xpAgMBAAE
rsa.authing.privateKey=MIIG_QIBADANBgkqhkiG9w0BAQEFAASCBucwggbjAgEAAoIBgQCviBX4xs177cbsUX_w7hjJYLyBFw0flxR6RoarJGyiiP66VX35N3mZGHyFAHo_rVPBE3j9KMgCgiHGSNXxYXZFDHq49XS8WQr6PDxadm2IiYkUXgH6kdfak684cV_-WelYXMnQn_BiSY6nPJ-YVEzikH_Syyg8UwRm9OrWbJEX3iuu2DOASd0kM8Hdf09rmVGk_y0I9WhGfg77F1Der-mNSaEc6HxJOOmZd62OT9SHF1skiTvNpb1GPGjBIP5-1Vi8J0M7wm7iAP_ScnmSsf_9wjI0IxplgYf092y7oKwd-qjuVyUhdCP_OlngPvsfgAQdad52y9lLQ842yRs8IoZk9J3XbNDHMj3N0bNeJ3RGUziInCN8cSdR1Tk9BqVzavEPrVXm8tMPkHy5R9atDamTalSg94Ha2DVUpkrUdoZb1ZSH974SK3tdbLixtpv8YF6Mc_zfE_4ANRCGpjCrOhdjF0QNqs53fIptfMUoRTtfLFfdNLf9SKen_qeBfzkvXGkCAwEAAQKCAYAJRyAiLh_eVQsWopgom-0jd8F-8UD4Unv6mo-zrBEx5hvQrYQjEBOVS_4I6aWMiBTNN8JFX0pzF33BhUgJoiUmMSqrbA3nhq1V3Kkz_t57QQnF0dI49Ex8eSHh0dxJDWeQDBd-t3V1PH4VyNaGrq4Bq7GV6rcNuTWaW4euHb7tjAizDSprtXvC1hmBI6GHBmuSVQqEVrRURYV1MB5OJu4pUaL6bC9lj2SJgBHkW8PYABwJKlfG3uPKOpcu3heVjKE1duMj9o2CP6KW36RU3MOhlDxldMfXDlTnk9ca_RU_WzsLEYYyq5jk5LN7EoKsmqHnSdQCojNCyfHyz6I2wpv4z1TZCAfdi1aoZigTZKPg8FUwzbNGfkwPN2i5A8g8z_t-KEd3HzSB8-7DP1M7GOYgUS1ii4g1clmUiyNsPxlYEg1XBCZWiT--NiLtcr8zQdU_Cw2uzZWHVlzF2z7O3zgo1p4OjWqlKWehLl9UE3hh9zTkO1PspUEzxK6hi8jWGCECgcEA8ZeqfNrw7OedDiiXsTtu-3wUl0Fim-ZkZDVAyWDLGkuGxJH44x02KzZaNb5h3MODGm_nEUr7BO0Ig5H0YkXwvPj5xh-7YTQEhM6_PW6uUWZ42bVK74-r4jtTM4rLnVHrOhNhVc_kYqJFsZVFcNieVoagAutqhdMnI0PzEHvkMXalMIn32BAECG-YiLCoHYkd9d5MCJkya1e-Ou8ZBneNV0eVlJ9x8lFXz-JYiGvfdIbsURJ6LtC5VbU7UyGTHIFDAoHBALn_4nAldjZYSgupbHxIahxMLXNot4EFRDy_53NrBVeaQ2W8zVZyc__xpKJfqBtSyP--madC8gH2pNTMXC4M3PEM9aEzAOKBKjp3Y8EvqcHErwuCoKpTZlXsFU27nE4Zl2m4SJCku76ifEONbsPiLp8VicYuxRRjIcj64ZDyiM3jj3v5f6w-ebycFKl9oKfH1-B3MGet6V7GjRs7xeXwue5XJ0qsFflXL3fpnFUl438S4YnArYzBZtsEEnItlWFq4wKBwQDF30_O1U_Q6V7UUuDzU1dx-M2wmOgYAlqlTIyUo4eWMNfftiMgeTN9rxWxwQ3MUAHYLGEX48622SFJCckcmGY1kMKayDCjy4QL9n3h5f42Q3Sl83u9vHGuaKKbq4lbf9XmiisFqrFHK9tjOHxYkcMV4Uu7OG_VzfzXQHcbQC3FaYSgvc_WEkALXMOU6QO4tS5pyzmBLWCDVKlFAcIAbvi_zKyxvuoH6yG97YhPq_KoMT3qpPSX1XKGxVoim3QvO5sCgcAjkdjG45Mgv2-hnUve1KZeNP84I9178frjtztW6i-CWkDrUtjd4FNordhzKOHoH8PKjLOrtfS8BWPuQgqaz-DsxDKxGiTgLB1cQvqzth67rJZhGCELkZlvcw975xX0JZa8I_7UknxI75_d900obrfFuoO3f7g2tuJ-IeRDKO6amRsWdVdCJEx5kkutQhYYH_KbvY9nNG39rvDLNXoaCBg2iTo9YH1vSooMX4ODERTZd03kXxGRamb2GWhBp4_6qksCgcA6TGFvO81SXpvZkyHfyVC_jn8fBQtZ0n4yXv5fsEAMO3lVHLy7SazRDykW6eYVyqey60FmSlzP1D5v6587pA2a56nojE4ORAIfhbVBhhKrb20TEz9iaa62-92zq8gAUKnkX7Ho5pTcg3WqXFT8Dez3_ZymlfPFZCJTEnSDbTTW3uazmW3qbybHwojCRa2gIXrECLDfHbIMr-3atO0azJyU_m9_iA9irvdsvoXhMTeCZCljrgHKTnCdNUxN5S8E0sE
## -- RSA end --

## -- cookie start --
cookie.token.name=_Y_G_
cookie.verify.token.name=_U_T_
cookie.token.domains=127.0.0.1;localhost;test.osinfra.cn;openeuler.org;opengauss.org
cookie.token.secures=false;false;true;true;true
## -- cookie end --

## -- oidc start --
oidc.token.base.password=ftrgybhnjiohnjk
oidc.login.page=https://id.openeuler.org/login
oidc.register.page=https://id.openeuler.org/register
oidc.code.expire=60
oidc.access.token.expire=1800
oidc.refresh.token.expire=86400
oidc.scope.profile=sub,name,family_name,given_name,middle_name,nickname,username,preferred_username,profile,picture,website,gender,birthdate,zoneinfo,locale,updated_at
oidc.scope.other=email->email,email_verified;phone->phone_number,phone_number_verified;address->formatted,street_address,locality,region,postal_code,country,province,city
oidc.scope.authing.mapping=sub:id,family_name:familyName,given_name:givenName,middle_name:middleName,preferred_username:preferredUsername,picture:photo,updated_at:updatedAt,email_verified:emailVerified,phone_number:phone,phone_number_verified:phoneVerified,street_address:streetAddress,postal_code:postalCode
## -- oidc end --

## -- temporary (??gitee????????) --
temp.extIdpIds=62c6501003ba211ff731f240;6226d911e5b246c2dbc9ba08;62613cee9d9f4360c5882798;62c3d6aa0ec65c37baaca4a3
temp.identifiers=opengauss-gitee;gitee;gitee-gauss;gitee-test
temp.users=17;39;48;88;89;90;92;115;121;125;156;338;340;341;342;345;358;460;468;475;544;548;556;580;606;643;668;718;739;799;802;860;875;881;884;885;906;919;937;941;1153;1154;1163;1166;1167;1173;1176;1177;1186;1188;1218;1221;1222;1223;1225;1226;1228;1229;1230;1231;1232;1234;1237;1238;1239;1241;1244;1250;1252;1255;1257;1271;1296;1302;1307;1312;1314;1327;1343;1344;1345;1348;1350;1364;1384;1394;1395;1447
## -- temporary --

## -- oneid server start --
oneid.api.host=https://oneid-server.osinfra.cn
opengauss.pool.key=550c60f82eab4fe2a038572da3d909a8
opengauss.pool.secret=2P45QNAR2F1oMDHljTPDIFXEsUhFBVPi
opengauss.apps=90aa315f895544359209920da32ff75a:59g6h46L4Y9i3j23eJ37kD1ac312s9yH
oneid.send.code.channel=login,register,register_by_password,reset_password,bind_phone,unbind_phone,bind_email,unbind_email,delete_account

app.manager.token.expire=2400
app.manager.refresh.token.expire=3600
## -- oneid  server end --

## -- privacy accepted version --
aigc.privacy.version=20230905
oneid.privacy.version=unused
## -- end privacy accepted version --

## -- gitee or github api --
gitee.api.token=3c4f66813a254d7e03b395dcdd7c633b
gitee.api.host=https://gitee.com/api/v5
github.api.token=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
github.api.host=https://api.github.com
## -- end gitee or github api --
rsa.authing.algorithm=RSA/ECB/OAEPWithSHA-256AndMGF1Padding
rsa.key.algorithm=RSA
authing.client.suffix=.authing.cn
community=openeuler

aes.authing.idToken=AES/GCM/NoPadding
aes.key.idToken=AES
aes.secret.idToken=N9f4+NK1m0NC5fwA9qVrBKTyf+qoTJNDR9J6IsWo8OI=
authing.token.session.password=0451130f75d9ea02
